/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.enotessa.SQLanomalies;

import com.enotessa.SQLanomalies.grigorov.MainClassGrigorov;
import com.enotessa.SQLanomalies.vmv.CheckDistribution;
import com.enotessa.SQLanomalies.vmv.CheckLength;
import com.enotessa.SQLanomalies.vmv.CheckToken;
import org.python.util.PythonInterpreter;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;

public class MainFrame extends javax.swing.JFrame {
    Connection connection = null;
    CheckLength checkLength = new CheckLength();
    CheckDistribution checkDistribution = new CheckDistribution();
    CheckToken checkToken = new CheckToken();

    /**
     * Creates new form main
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jlogin = new javax.swing.JTextField();
        Jpassword = new javax.swing.JPasswordField();
        Jconnection = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Jtrain = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        J1Method = new javax.swing.JButton();
        J2Method = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextResultTrain = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextMethod1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextQuery = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 153));

        jPanel1.setBackground(new java.awt.Color(38, 70, 83));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setLabelFor(Jlogin);
        jLabel2.setText("логин");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("пароль");

        Jlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JloginActionPerformed(evt);
            }
        });

        Jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpasswordActionPerformed(evt);
            }
        });

        Jconnection.setBackground(new java.awt.Color(42, 157, 143));
        Jconnection.setForeground(new java.awt.Color(255, 255, 255));
        Jconnection.setText("подключиться к БД");
        Jconnection.setBorderPainted(false);
        Jconnection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jconnection.setDefaultCapable(false);
        Jconnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JconnectionActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Подключение к БД");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/18939.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(145, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(25, 25, 25)
                                                                .addComponent(Jconnection, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(Jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(Jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel1)))
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(155, 155, 155))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(238, 238, 238))))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Jlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Jpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Jconnection)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setBackground(new java.awt.Color(38, 70, 83));

        Jtrain.setBackground(new java.awt.Color(42, 157, 143));
        Jtrain.setForeground(new java.awt.Color(255, 255, 255));
        Jtrain.setText("тренировать");
        Jtrain.setBorder(null);
        Jtrain.setBorderPainted(false);
        Jtrain.setDefaultCapable(false);
        Jtrain.setFocusPainted(false);
        Jtrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtrainActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(242, 239, 233));
        jLabel3.setLabelFor(jTextQuery);
        jLabel3.setText("введите запрос для проверки");

        J1Method.setBackground(new java.awt.Color(42, 157, 143));
        J1Method.setForeground(new java.awt.Color(255, 255, 255));
        J1Method.setText("1. метод Винья, Валер, Мутц");
        J1Method.setBorder(null);
        J1Method.setBorderPainted(false);
        J1Method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J1MethodActionPerformed(evt);
            }
        });

        J2Method.setBackground(new java.awt.Color(42, 157, 143));
        J2Method.setForeground(new java.awt.Color(255, 255, 255));
        J2Method.setText("2. метод Григорова");
        J2Method.setBorder(null);
        J2Method.setBorderPainted(false);
        J2Method.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                J2MethodActionPerformed(evt);
            }
        });

        jTextResultTrain.setBackground(new java.awt.Color(242, 239, 233));
        jTextResultTrain.setColumns(20);
        jTextResultTrain.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextResultTrain.setRows(5);
        jScrollPane4.setViewportView(jTextResultTrain);

        jTextMethod1.setBackground(new java.awt.Color(242, 239, 233));
        jTextMethod1.setColumns(20);
        jTextMethod1.setRows(5);
        jScrollPane5.setViewportView(jTextMethod1);

        jSeparator1.setBackground(new java.awt.Color(42, 157, 143));

        jLabel6.setBackground(new java.awt.Color(242, 239, 233));
        jLabel6.setForeground(new java.awt.Color(242, 239, 233));
        jLabel6.setText("результат");

        jTextQuery.setBackground(new java.awt.Color(242, 239, 233));
        jTextQuery.setColumns(20);
        jTextQuery.setRows(5);
        jScrollPane2.setViewportView(jTextQuery);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jScrollPane5)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(J1Method, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                                .addComponent(J2Method, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(Jtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Jtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(J2Method, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addComponent(J1Method, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void JconnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JconnectionActionPerformed
        jTextField2.setText("...");
        String login = Jlogin.getText();
        String password = Jpassword.getText();

        try {
            connection = ConnectionClass.getConnection("Admin", "Admin");

        } catch (SQLException e) {
            e.printStackTrace();
            jTextField2.setText("ошибка при подключении");
            System.out.println("ошибка при подключении");
        }
        jTextField2.setText("подключено");
        System.out.println("подключено");
    }//GEN-LAST:event_JconnectionActionPerformed

    private void JtrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtrainActionPerformed
        ReadSQL readSQL = null;
        try {
            readSQL = new ReadSQL();
            checkLength.train(readSQL.arrayList);
            jTextResultTrain.setText("обучена модель: Длина строки");
            checkDistribution.train(readSQL.arrayList);
            jTextResultTrain.setText(jTextResultTrain.getText() + "\nобучена модель: Распределение символов строки");
            checkToken.train(readSQL.arrayList);
            jTextResultTrain.setText(jTextResultTrain.getText() + "\nобучена модель: Поиск токенов. независимая модель");
            jTextResultTrain.setText(jTextResultTrain.getText() + "\nОБУЧЕНО!");
        } catch (IOException e) {
            jTextResultTrain.setText("не удалось открыть файл");
        }

    }//GEN-LAST:event_JtrainActionPerformed


    private void J1MethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J1MethodActionPerformed
        String query = jTextQuery.getText();
        jTextMethod1.setText("Проверка на длину строки : " + checkLength.validate(query));
        boolean t = checkDistribution.validate(query);
        jTextMethod1.setText(jTextMethod1.getText() + "\nПроверка модели: Проверка на распределение символов строки : " + checkDistribution.validate(query));
        jTextMethod1.setText(jTextMethod1.getText() + "\nПроверка модели: Поиск токенов. независимая модель : " + checkToken.validate(query));
    }//GEN-LAST:event_J1MethodActionPerformed


    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void JpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpasswordActionPerformed

    private void JloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JloginActionPerformed

    private void J2MethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_J2MethodActionPerformed
        String query = jTextQuery.getText();
        MainClassGrigorov mainClassGrigorov = new MainClassGrigorov(connection);
        boolean k = false;
        try {
            k = mainClassGrigorov.methodRun(query);
        } catch (ParseException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        if (k)
            jTextMethod1.setText("запрос признан нормальным");
        else jTextMethod1.setText("запрос признан аномальным");
    }//GEN-LAST:event_J2MethodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton J1Method;
    private javax.swing.JButton J2Method;
    private javax.swing.JButton Jconnection;
    private javax.swing.JTextField Jlogin;
    private javax.swing.JPasswordField Jpassword;
    private javax.swing.JButton Jtrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea jTextMethod1;
    private javax.swing.JTextArea jTextQuery;
    private javax.swing.JTextArea jTextResultTrain;
    // End of variables declaration//GEN-END:variables
}
